FROM golang:1.24-bookworm

RUN go install golang.org/x/tools/gopls@latest
RUN go install github.com/go-delve/delve/cmd/dlv@latest

RUN apt update && apt install unzip

RUN echo "PS1='\[\e[1;32m\]\w\[\e[0m\] # '" >> /root/.bashrc