name: Limit PR Commits

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  limit-pr-commits:
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - uses: AntonKosov/limit-pr-commits-action@v1.0.1
        with:
          max-commits: "1"
