name: Limit PR Commits

on:
  pull_request:
    branches:
      - master

jobs:
  limit-pr-commits:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - uses: AntonKosov/limit-pr-commits-action@v1.0.4
