name: Quality of Code

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  quality-of-code:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - name: Vetting
        run: go vet ./...

      - name: Linting
        run: go tool staticcheck ./...

      - name: Tests
        run: go test ./...
